{% set name = "dask-cuda" %}
{% set version = "22.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-cuda-{{ version }}.tar.gz
  sha256: 5b369b3f3d2c62841f742ad4cfe5b6334dd40e7b397ac5dc46bd41167d527cc2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-cuda-worker = dask_cuda.cli.dask_cuda_worker:go

requirements:
  host:
    - python >=3.8,<3.10
    - pip
  run:
    - python >=3.8,<3.10
    - dask ==2022.03.0
    - distributed ==2022.03.0
    - numba >=0.53.1
    - numpy >=1.16.0
    - pynvml >=11.0.0
    - click ==8.0.4
    - __linux

test:
  imports:
    - dask_cuda
    - dask_cuda.benchmarks
  commands:
    - pip check
    - dask-cuda-worker --help
  requires:
    - pip

about:
  home: https://github.com/rapidsai/dask-cuda
  summary: Utilities for Dask and CUDA interactions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
